#!/usr/bin/env python

import roslib
roslib.load_manifest('turtlebot3_teleop')
import rospy

from std_msgs.msg import String

import sys, select, termios, tty

def getKey():
    tty.setraw(sys.stdin.fileno())
    rlist, _, _ = select.select([sys.stdin], [], [], 0.1)
    if rlist:
        key = sys.stdin.read(1)
    else:
        key = ''

    termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)
    return key

rospy.init_node('turtlebot3_teleop_keyboard')
pub = rospy.Publisher('/Key',String, queue_size=1)
rate = rospy.Rate(2)
string = String()

while not rospy.is_shutdown(): 
  pub.publish(string)
  rate.sleep()
